CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Direcciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Provincia" text NOT NULL,
    "Canton" text NOT NULL,
    "Parroquia" text NOT NULL,
    CONSTRAINT "PK_Direcciones" PRIMARY KEY ("Id")
);

CREATE TABLE "Elecciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" text NOT NULL,
    "FechaInicio" timestamp without time zone NOT NULL,
    "FechaFin" timestamp without time zone NOT NULL,
    "Estado" text NOT NULL,
    CONSTRAINT "PK_Elecciones" PRIMARY KEY ("Id")
);

CREATE TABLE "Listas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NombreLista" text NOT NULL,
    "LogoUrl" text NOT NULL,
    "EleccionId" integer NOT NULL,
    CONSTRAINT "PK_Listas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Listas_Elecciones_EleccionId" FOREIGN KEY ("EleccionId") REFERENCES "Elecciones" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VotosAnonimos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FechaVoto" timestamp without time zone NOT NULL,
    "EleccionId" integer NOT NULL,
    "DireccionId" integer NOT NULL,
    "NumeroMesa" integer NOT NULL,
    "ListaId" integer NOT NULL,
    "CedulaCandidato" text NOT NULL,
    "RolPostulante" text NOT NULL,
    CONSTRAINT "PK_VotosAnonimos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VotosAnonimos_Elecciones_EleccionId" FOREIGN KEY ("EleccionId") REFERENCES "Elecciones" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Juntas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroMesa" integer NOT NULL,
    "DireccionId" integer NOT NULL,
    "JefeDeJuntaId" character varying(10) NOT NULL,
    "Estado" integer NOT NULL,
    CONSTRAINT "PK_Juntas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Juntas_Direcciones_DireccionId" FOREIGN KEY ("DireccionId") REFERENCES "Direcciones" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Votantes" (
    "Cedula" character varying(10) NOT NULL,
    "NombreCompleto" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "FotoUrl" text NOT NULL,
    "RolId" integer NOT NULL,
    "Estado" boolean NOT NULL,
    "HaVotado" boolean NOT NULL,
    "JuntaId" integer,
    "Discriminator" character varying(13) NOT NULL,
    "ListaId" integer,
    "RolPostulante" text,
    CONSTRAINT "PK_Votantes" PRIMARY KEY ("Cedula"),
    CONSTRAINT "FK_Votantes_Juntas_JuntaId" FOREIGN KEY ("JuntaId") REFERENCES "Juntas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Votantes_Listas_ListaId" FOREIGN KEY ("ListaId") REFERENCES "Listas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TokensAcceso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(6) NOT NULL,
    "VotanteId" character varying(10) NOT NULL,
    "EsValido" boolean NOT NULL,
    "FechaCreacion" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TokensAcceso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TokensAcceso_Votantes_VotanteId" FOREIGN KEY ("VotanteId") REFERENCES "Votantes" ("Cedula") ON DELETE CASCADE
);

CREATE INDEX "IX_Juntas_DireccionId" ON "Juntas" ("DireccionId");

CREATE INDEX "IX_Juntas_JefeDeJuntaId" ON "Juntas" ("JefeDeJuntaId");

CREATE INDEX "IX_Listas_EleccionId" ON "Listas" ("EleccionId");

CREATE INDEX "IX_TokensAcceso_VotanteId" ON "TokensAcceso" ("VotanteId");

CREATE INDEX "IX_Votantes_JuntaId" ON "Votantes" ("JuntaId");

CREATE INDEX "IX_Votantes_ListaId" ON "Votantes" ("ListaId");

CREATE INDEX "IX_VotosAnonimos_EleccionId" ON "VotosAnonimos" ("EleccionId");

ALTER TABLE "Juntas" ADD CONSTRAINT "FK_Juntas_Votantes_JefeDeJuntaId" FOREIGN KEY ("JefeDeJuntaId") REFERENCES "Votantes" ("Cedula") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260120163702_beta', '10.0.2');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260122064243_v2', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE "Votantes" ADD "EleccionId" integer;

CREATE INDEX "IX_Votantes_EleccionId" ON "Votantes" ("EleccionId");

ALTER TABLE "Votantes" ADD CONSTRAINT "FK_Votantes_Elecciones_EleccionId" FOREIGN KEY ("EleccionId") REFERENCES "Elecciones" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125020342_alfa', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE "Votantes" DROP CONSTRAINT "FK_Votantes_Elecciones_EleccionId";

ALTER TABLE "Votantes" DROP CONSTRAINT "FK_Votantes_Listas_ListaId";

DROP INDEX "IX_Votantes_EleccionId";

DROP INDEX "IX_Votantes_ListaId";

ALTER TABLE "Votantes" DROP COLUMN "Discriminator";

ALTER TABLE "Votantes" DROP COLUMN "EleccionId";

ALTER TABLE "Votantes" DROP COLUMN "ListaId";

ALTER TABLE "Votantes" DROP COLUMN "RolPostulante";

CREATE TABLE "Candidatos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cedula" character varying(10) NOT NULL,
    "ListaId" integer NOT NULL,
    "EleccionId" integer NOT NULL,
    "RolPostulante" text NOT NULL,
    CONSTRAINT "PK_Candidatos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Candidatos_Elecciones_EleccionId" FOREIGN KEY ("EleccionId") REFERENCES "Elecciones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Candidatos_Listas_ListaId" FOREIGN KEY ("ListaId") REFERENCES "Listas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Candidatos_Votantes_Cedula" FOREIGN KEY ("Cedula") REFERENCES "Votantes" ("Cedula") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Candidatos_Cedula_EleccionId" ON "Candidatos" ("Cedula", "EleccionId");

CREATE INDEX "IX_Candidatos_EleccionId" ON "Candidatos" ("EleccionId");

CREATE INDEX "IX_Candidatos_ListaId" ON "Candidatos" ("ListaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125022724_Gama', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE "Juntas" DROP CONSTRAINT "FK_Juntas_Direcciones_DireccionId";

ALTER TABLE "Juntas" ALTER COLUMN "JefeDeJuntaId" DROP NOT NULL;

ALTER TABLE "Juntas" ADD CONSTRAINT "FK_Juntas_Direcciones_DireccionId" FOREIGN KEY ("DireccionId") REFERENCES "Direcciones" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125031920_alfa2', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE "Juntas" ADD "EleccionId" integer NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX "IX_Juntas_EleccionId_DireccionId_NumeroMesa" ON "Juntas" ("EleccionId", "DireccionId", "NumeroMesa");

ALTER TABLE "Juntas" ADD CONSTRAINT "FK_Juntas_Elecciones_EleccionId" FOREIGN KEY ("EleccionId") REFERENCES "Elecciones" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260128003125_gama2', '10.0.2');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260128184528_Alfa3', '10.0.2');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260128191857_Beta3', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE "Votantes" ALTER COLUMN "JuntaId" TYPE bigint;

ALTER TABLE "Juntas" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Juntas" ALTER COLUMN "Id" DROP IDENTITY;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260129004602_Gama3', '10.0.2');

COMMIT;

