// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaVotoAPI.Migrations
{
    [DbContext(typeof(APIVotosDbContext))]
    [Migration("20260107021842_MigracionBeta")]
    partial class MigracionBeta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotoModelos.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DatosVotanteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatosVotanteId");

                    b.HasIndex("ListaId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVotoModelos.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TipoEleccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("SistemaVotoModelos.HistorialParticipacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("VotanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("VotanteId");

                    b.ToTable("HistorialParticipaciones");
                });

            modelBuilder.Entity("SistemaVotoModelos.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("SistemaVotoModelos.Votante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("SistemaVotoModelos.VotoAnonimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EleccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleccionId");

                    b.HasIndex("ListaId");

                    b.ToTable("VotosAnonimos");
                });

            modelBuilder.Entity("SistemaVotoModelos.Candidato", b =>
                {
                    b.HasOne("SistemaVotoModelos.Votante", "DatosVotante")
                        .WithMany()
                        .HasForeignKey("DatosVotanteId");

                    b.HasOne("SistemaVotoModelos.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaId");

                    b.Navigation("DatosVotante");

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("SistemaVotoModelos.HistorialParticipacion", b =>
                {
                    b.HasOne("SistemaVotoModelos.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.HasOne("SistemaVotoModelos.Votante", "Votante")
                        .WithMany()
                        .HasForeignKey("VotanteId");

                    b.Navigation("Eleccion");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("SistemaVotoModelos.Lista", b =>
                {
                    b.HasOne("SistemaVotoModelos.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("SistemaVotoModelos.VotoAnonimo", b =>
                {
                    b.HasOne("SistemaVotoModelos.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId");

                    b.HasOne("SistemaVotoModelos.Eleccion", "Eleccion")
                        .WithMany()
                        .HasForeignKey("EleccionId");

                    b.HasOne("SistemaVotoModelos.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaId");

                    b.Navigation("Candidato");

                    b.Navigation("Eleccion");

                    b.Navigation("Lista");
                });
#pragma warning restore 612, 618
        }
    }
}
